title: Graycoral Blog
author: Youngho Kim
email: graycoral.kim@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Youngho's Study and Work Pages
show_excerpts: true # set to true to show excerpts on the homepage

readme_index:
  with_frontmatter: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Kim, Youngho
  tagline: SW Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: games
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/YounghoKim.jpg" # the path from the base directory of the site to the image to display (no / at the start)

  # generate social links in footer
  social_links:
    twitter: graycoral
    github:  graycoral
    linkedIn: in/graycoral
    instagram: graycoral
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

navigation:
  - title: AUTOSAR
    url: "/_posts/AUTOSAR"
  - title: C++ Degign Pattern
    url: "/_posts/C++DesignPattern(2019.03)"
  - title: C++ Template
    url: "/_posts/C++Template(2019.10)"

# Build settings
theme: plainwhite

remote_theme: thelehhman/plainwhite-jekyll

gems: ['jekyll-plantuml', 'jekyll-seo-tag']
plugins:
  - jekyll-seo-tag
  - jekyll-plantuml
  # - jekyll-feed
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://graycoral.github.io/" # the base hostname & protocol for your site
